# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Fri Jun  5 21:15:51 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MakeRowColGrowableDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MakeRowColGrowableDlg.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Make row and/or column growable")
        
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        
        static_text_1 = wx.StaticText(self, wx.ID_ANY, "You have set a widget's layout to EXPAND.\n\nThe containing row and column are not growable.\nSo EXPAND does not have an effect.")
        sizer_1.Add(static_text_1, 0, wx.ALL | wx.EXPAND, 8)
        
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Make growable"), wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 6)
        
        self.cb_row_growable = wx.CheckBox(self, wx.ID_ANY, "Row")
        sizer_2.Add(self.cb_row_growable, 0, wx.ALL, 4)
        
        self.cb_col_growable = wx.CheckBox(self, wx.ID_ANY, "Column")
        sizer_2.Add(self.cb_col_growable, 0, wx.ALL, 4)
        
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 0, wx.ALL | wx.EXPAND, 2)
        
        self.cb_dont_show_again = wx.CheckBox(self, wx.ID_ANY, "Don't show this dialog again")
        sizer_3.Add(self.cb_dont_show_again, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)
        
        sizer_3.Add((20, 20), 1, wx.ALIGN_CENTER_VERTICAL, 0)
        
        self.button_OK = wx.Button(self, wx.ID_OK, "")
        sizer_3.Add(self.button_OK, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        
        self.Layout()
        # end wxGlade

# end of class MakeRowColGrowableDlg
