# tree.py: classes to handle and display the structure of a wxGlade app
# 
# Copyright (c) 2002 Alberto Griggio <albgrig@tiscalinet.it>
# License: GPL (see license.txt)

from wxPython.wx import *
from xml.sax.saxutils import quoteattr

class Tree:
    """\
    A class to represent a hierarchy of widgets.
    """
    class Node:
        def __init__(self, widget=None, children=None):
            self.widget = widget
            self.children = children
            self.parent = None

        def remove(self):
            def remove_rec(node):
                if node.children is not None:
                    map(remove_rec, node.children)
                node.children = None
                if node.widget is not None:
                    # replace the just destroyed notebook with an empty window
                    pw = node.widget.property_window
                    pw.SetTitle('Properties - <>')
                    pw.GetSizer().GetChildren()[0].SetWindow(
                        wxNotebook(node.widget.property_window, -1))
                    # call the widget's ``destructor''
                    node.widget.delete()
                node.widget = None
            remove_rec(self)
            try: self.parent.children.remove(self)
            except: pass
                    
        def __repr__(self):
            try: return self.widget.name
            except AttributeError: return `self.widget`

        def write(self, outfile, tabs):
            """\
            Writes the xml code for the widget to the given output file
            """
            import edit_sizers
            fwrite = outfile.write
            assert self.widget is not None
            w = self.widget
            fwrite('    ' * tabs + '<object class=%s name=%s base=%s>\n'
                   % (quoteattr(w.klass), quoteattr(w.name),
                      quoteattr(w.__class__.__name__)))
            for p in w.properties:
                w.properties[p].write(outfile, tabs+1)

            if isinstance(w, edit_sizers.SizerBase):
                if self.children is not None:
                    for c in self.children:
                        fwrite('    ' * (tabs+1) +
                               '<object class="sizeritem">\n')
                        sp = c.widget.sizer_properties
                        for p in sp: sp[p].write(outfile, tabs+2)
                        c.write(outfile, tabs+2)
                        fwrite('    ' * (tabs+1) + '</object>\n')
            elif self.children is not None:
                for c in self.children: c.write(outfile, tabs+1)
            fwrite('    ' * tabs + '</object>\n')

    # end of class Node

    def __init__(self, root=None, app=None):
        self.root = root
        if self.root is None: self.root = Tree.Node()
        self.current = self.root
        self.app = app # reference to the app properties
        self.names = {} # dictionary of names of the widgets 

    def has_name(self, name): return self.names.has_key(name)

    def add(self, child, parent=None):
        if parent is None: parent = self.root 
        if parent.children is None: parent.children = []
        parent.children.append(child)
        child.parent = parent
        self.current = child
        self.names[str(child.widget.name)] = 1
        if parent is self.root:
            self.app.add_top_window(child.widget.name)

    def insert(self, child, parent, index):
        if parent is None: parent = self.root
        if parent.children is None:
            parent.children = []
        parent.children.insert(index, child)
        child.parent = parent
        self.current = child
        self.names[str(child.widget.name)] = 1
        if parent is self.root:
            self.app.add_top_window(child.widget.name)

    def remove(self, node=None):
        if node is not None:
            try: del self.names[str(node.widget.name)]
            except (KeyError, AttributeError): pass
            if node.parent is self.root:
                self.app.remove_top_window(node.widget.name)
            node.remove()
        elif self.root.children:
            [n.remove() for n in self.root.children]
            self.root.children = None
            self.names = {}

    def write(self, outfile=None, tabs=0):
        """\
        Writes the xml equivalent of this tree to the given output file
        """
        if outfile is None:
            import sys
            outfile = sys.stdout
        from time import asctime
        import common
        outfile.write('<?xml version="1.0"?>\n<!-- generated by wxGlade %s ' \
                      'on %s -->\n\n' % (common.version, asctime()))
        outpath = self.app.output_path.strip()
        name = self.app.get_name()
        klass = self.app.get_class()
        option = str(self.app.codegen_opt)
        top_window = self.app.get_top_window()
        outfile.write('<application path=%s name=%s class=%s option=%s ' \
                      'top_window=%s>\n'% (quoteattr(outpath), quoteattr(name),
                                           quoteattr(klass), quoteattr(option),
                                           quoteattr(top_window)))
        if self.root.children is not None:
            [c.write(outfile, tabs+1) for c in self.root.children]
        outfile.write('</application>\n')

# end of class Tree


class WidgetTree(wxTreeCtrl, Tree):
    """\
    Tree with the ability to display the hierarchy of widgets
    """
    images = {} # dictionary of icons of the widgets displayed
    def __init__(self, parent, application):
        id = wxNewId()
        wxTreeCtrl.__init__(self, parent, id)
        root_node = Tree.Node(application)
        self.cur_widget = None # reference to the selected widget
        Tree.__init__(self, root_node, application)
        image_list = wxImageList(21, 21)
        image_list.Add(wxBitmap('icons/application.xpm',
                                wxBITMAP_TYPE_XPM))
        for w in WidgetTree.images:
            WidgetTree.images[w] = image_list.Add(wxBitmap(
                WidgetTree.images[w], wxBITMAP_TYPE_XPM))
        self.AssignImageList(image_list)
        root_node.item = self.AddRoot('Application', 0)
        self.SetPyData(root_node.item, root_node)
        self.skip_select = 0 # necessary to avoid an infinite loop on win32, as
                             # SelectItem fires an EVT_TREE_SEL_CHANGED event
        EVT_TREE_SEL_CHANGED(self, id, self.on_change_selection)
        EVT_RIGHT_DOWN(self, self.popup_menu)
        EVT_LEFT_DCLICK(self, self.show_toplevel)
        self.title = ' '
        self.set_title(self.title)
        
        self.auto_expand = True # this control the automatic expansion of
                                # nodes: it is set to False during xml loading

    def add(self, child, parent=None, image=None): # is image still used?
        """\
        appends child to the list of parent's children
        """
        Tree.add(self, child, parent)
        import common
        name = child.widget.__class__.__name__
        index = WidgetTree.images.get(name, -1)
        if parent is None: parent = parent.item = self.GetRootItem()
        child.item = self.AppendItem(parent.item, child.widget.name, index)
        self.SetPyData(child.item, child)
        if self.auto_expand:
            self.Expand(parent.item)
            self.select_item(child)
        child.widget.show_properties()

    def insert(self, child, parent, pos, image=None):
        """\
        inserts child to the list of parent's children, before index
        """
        if parent.children is None:
            self.add(child, parent, image)
            return
        import common
        name = child.widget.__class__.__name__
        image_index = WidgetTree.images.get(name, -1)
        if parent is None: parent = parent.item = self.GetRootItem()

        index = 0
        item, cookie = self.GetFirstChild(parent.item, 1)
        while item.IsOk():
            item_pos = self.GetPyData(item).widget.pos
            if pos < item_pos: break
            index += 1            
            item, cookie = self.GetNextChild(parent.item, cookie)

        Tree.insert(self, child, parent, index)
        child.item = self.InsertItemBefore(parent.item, index,
                                           child.widget.name, image_index)
        if self.auto_expand: self.Expand(parent.item)
        self.SetPyData(child.item, child)
        self.select_item(child)
        child.widget.show_properties()

    def remove(self, node=None):
        self.app.saved = False # update the status of the app
        Tree.remove(self, node)
        if node is not None:
            try:
                self.cur_widget = None
                self.SelectItem(node.parent.item)
            except: self.SelectItem(self.GetRootItem())
            self.Delete(node.item)
        else:
            wxTreeCtrl.Destroy(self)

    def clear(self):
        self.app.reset()
        self.skip_select = True
        if self.root.children:
            while self.root.children:
                c = self.root.children[-1]
                if c.widget: c.widget.remove()
            self.root.children = None
        self.skip_select = False
        app = self.GetPyData(self.GetRootItem())
        app.widget.show_properties()

    def set_name(self, node, name):
        self.SetItemText(node.item, name)

    def select_item(self, node):
        self.skip_select = True
        self.SelectItem(node.item)
        self.skip_select = False
        if self.cur_widget: self.cur_widget.update_view(False)
        self.cur_widget = node.widget
        self.cur_widget.update_view(True)

    def on_change_selection(self, event):
        if not self.skip_select:
            item = event.GetItem()
            try:
                if self.cur_widget: self.cur_widget.update_view(False)
                self.cur_widget = self.GetPyData(item).widget
                self.cur_widget.show_properties(None)
                self.cur_widget.update_view(True)
            except AttributeError:
                pass
            except Exception:
                import traceback
                traceback.print_exc()

    def popup_menu(self, event):
        item = self.GetPyData(self.GetSelection()).widget
        if not item.widget or not item.is_visible(): return
        try:
            x, y = self.ClientToScreen(event.GetPosition())
            x, y = item.widget.ScreenToClient((x, y))
            event.m_x, event.m_y = x, y
            item.popup_menu(event)
        except AttributeError:
            import traceback; traceback.print_exc()

    def expand(self, node=None, yes=True):
        """\
        expands or collapses the given node
        """
        if node is None: node = self.root
        if yes: self.Expand(node.item)
        else: self.Collapse(node.item)

    def set_title(self, value):
        self.title = value
        try: self.GetParent().SetTitle('wxGlade: Tree %s' % value)
        except: pass

    def get_title(self):
        if not self.title: self.title = ' '
        return self.title

    def show_widget(self, node, toplevel=False):
        """\
        Shows the widget of the given node and all its children
        """
        if toplevel:
            if not node.widget.widget:
                node.widget.create_widget()
                node.widget.finish_widget_creation()
            if node.children:
                for c in node.children: self.show_widget(c)
            node.widget.show_widget(True)
            node.widget.show_properties()
        else:
            def show_rec(node):
                node.widget.show_widget(True)
                self.expand(node, True)
                if node.children:
                    for c in node.children: show_rec(c)
            show_rec(node)

    def show_toplevel(self, event):
        """\
        Event handler for left double-clicks: if the click is above a toplevel
        widget and this is hidden, shows it
        """
        def inside(x, y, rect):
            return (rect.x <= x <= rect.x + rect.width) and \
                   (rect.y <= y <= rect.y + rect.height)
        x, y = event.GetPosition()
        for node in self.root.children:
            rect = self.GetBoundingRect(node.item)
            if rect is not None and inside(x, y, rect):
                if not node.widget.is_visible():
                    self.show_widget(node, True)
                else:
                    node.widget.show_widget(False)
                    self.select_item(self.root)
                    self.app.show_properties()                    
                break
        event.Skip()
        
# end of class WidgetTree


class MenuTree:
    """\
    A class to represent a menu on a wxMenuBar
    """
    class Node:
        def __init__(self, label="", id="", name="", checkable=""):
            self.label = label
            self.id = id
            self.name = name
            self.checkable = checkable
            self.children = []
            self.parent = None
            
        def write(self, outfile, tabs, top=False):
            from xml.sax.saxutils import escape, quoteattr
            import widget_properties
            fwrite = outfile.write
            tstr = '    ' * (tabs+1)
            label = widget_properties._encode(self.label)
            if not top and not self.children:
                fwrite('%s<item>\n' % ('    ' * tabs))
                fwrite('%s<label>%s</label>\n' % (tstr, escape(label)))
                fwrite('%s<id>%s</id>\n' % (tstr, escape(self.id)))
                fwrite('%s<name>%s</name>\n' % (tstr, escape(self.name)))
                try: checkable = int(self.checkable)
                except: checkable = 0
                fwrite('%s<checkable>%s</checkable>\n' % (tstr, checkable))
                fwrite('%s</item>\n' % ('    ' * tabs))
            else:
                name = quoteattr(self.name)
                fwrite('    ' * tabs + '<menu name=%s ' % name)
                fwrite('label=%s>\n' % (quoteattr(label)))
                for c in self.children: c.write(outfile, tabs+1)
                fwrite('    ' * tabs + '</menu>\n')
                
    #end of class Node
    
    def __init__(self, name, label):
        self.root = self.Node(label, "", name, "")

    def write(self, outfile, tabs):
        self.root.write(outfile, tabs, top=True)
        
#end of class MenuTree

