#!/usr/bin/env lisp
;;;
;;; generated by wxGlade
;;;

(asdf:operate 'asdf:load-op 'wxcl)
(use-package "FFI")
(ffi:default-foreign-language :stdc)


;;; begin wxGlade: dependencies
(use-package :wxBitmapButton)
(use-package :wxButton)
(use-package :wxCL)
(use-package :wxCheckBox)
(use-package :wxCheckListBox)
(use-package :wxChoice)
(use-package :wxColour)
(use-package :wxComboBox)
(use-package :wxDatePickerCtrl)
(use-package :wxEvent)
(use-package :wxEvtHandler)
(use-package :wxFrame)
(use-package :wxGauge)
(use-package :wxGrid)
(use-package :wxHyperlinkCtrl)
(use-package :wxListBox)
(use-package :wxListCtrl)
(use-package :wxMenu)
(use-package :wxMenuBar)
(use-package :wxNotebook)
(use-package :wxPanel)
(use-package :wxRadioBox)
(use-package :wxRadioButton)
(use-package :wxScrolledWindow)
(use-package :wxSizer)
(use-package :wxSlider)
(use-package :wxSpinButton)
(use-package :wxSpinCtrl)
(use-package :wxSplitterWindow)
(use-package :wxStaticBitmap)
(use-package :wxStaticLine)
(use-package :wxStaticText)
(use-package :wxStatusBar)
(use-package :wxTextCtrl)
(use-package :wxToggleButton)
(use-package :wxToolBar)
(use-package :wxTreeCtrl)
(use-package :wxWindow)
(use-package :wx_main)
(use-package :wx_wrapper)
;;; end wxGlade

;;; begin wxGlade: extracode
;;; end wxGlade


(defclass All_Widgets_Frame()
        ((top-window :initform nil :accessor slot-top-window)
        (All-Widgets-menubar :initform nil :accessor slot-All-Widgets-menubar)
        (All-Widgets-statusbar :initform nil :accessor slot-All-Widgets-statusbar)
        (All-Widgets-toolbar :initform nil :accessor slot-All-Widgets-toolbar)
        (sizer-1 :initform nil :accessor slot-sizer-1)
        (notebook-1 :initform nil :accessor slot-notebook-1)
        (notebook-1-wxBitmapButton :initform nil :accessor slot-notebook-1-wxBitmapButton)
        (sizer-13 :initform nil :accessor slot-sizer-13)
        (bitmap-button-icon1 :initform nil :accessor slot-bitmap-button-icon1)
        (bitmap-button-empty1 :initform nil :accessor slot-bitmap-button-empty1)
        (bitmap-button-icon2 :initform nil :accessor slot-bitmap-button-icon2)
        (bitmap-button-art :initform nil :accessor slot-bitmap-button-art)
        (notebook-1-wxButton :initform nil :accessor slot-notebook-1-wxButton)
        (sizer-28 :initform nil :accessor slot-sizer-28)
        (button-3 :initform nil :accessor slot-button-3)
        (notebook-1-wxCalendarCtrl :initform nil :accessor slot-notebook-1-wxCalendarCtrl)
        (sizer-12 :initform nil :accessor slot-sizer-12)
        (notebook-1-wxCheckBox :initform nil :accessor slot-notebook-1-wxCheckBox)
        (sizer-21 :initform nil :accessor slot-sizer-21)
        (checkbox-1 :initform nil :accessor slot-checkbox-1)
        (checkbox-2 :initform nil :accessor slot-checkbox-2)
        (checkbox-3 :initform nil :accessor slot-checkbox-3)
        (checkbox-4 :initform nil :accessor slot-checkbox-4)
        (checkbox-5 :initform nil :accessor slot-checkbox-5)
        (checkbox-6 :initform nil :accessor slot-checkbox-6)
        (notebook-1-wxCheckListBox :initform nil :accessor slot-notebook-1-wxCheckListBox)
        (sizer-26 :initform nil :accessor slot-sizer-26)
        (check-list-box-1 :initform nil :accessor slot-check-list-box-1)
        (notebook-1-wxChoice :initform nil :accessor slot-notebook-1-wxChoice)
        (sizer-5 :initform nil :accessor slot-sizer-5)
        (choice-empty :initform nil :accessor slot-choice-empty)
        (choice-filled :initform nil :accessor slot-choice-filled)
        (notebook-1-wxComboBox :initform nil :accessor slot-notebook-1-wxComboBox)
        (sizer-6 :initform nil :accessor slot-sizer-6)
        (sizer-7 :initform nil :accessor slot-sizer-7)
        (combo-box-empty :initform nil :accessor slot-combo-box-empty)
        (combo-box-filled :initform nil :accessor slot-combo-box-filled)
        (notebook-1-wxDatePickerCtrl :initform nil :accessor slot-notebook-1-wxDatePickerCtrl)
        (sizer-17 :initform nil :accessor slot-sizer-17)
        (datepicker-ctrl-1 :initform nil :accessor slot-datepicker-ctrl-1)
        (notebook-1-wxGauge :initform nil :accessor slot-notebook-1-wxGauge)
        (sizer-15 :initform nil :accessor slot-sizer-15)
        (gauge-1 :initform nil :accessor slot-gauge-1)
        (notebook-1-wxGrid :initform nil :accessor slot-notebook-1-wxGrid)
        (sizer-19 :initform nil :accessor slot-sizer-19)
        (grid-1 :initform nil :accessor slot-grid-1)
        (notebook-1-wxHyperlinkCtrl :initform nil :accessor slot-notebook-1-wxHyperlinkCtrl)
        (sizer-20 :initform nil :accessor slot-sizer-20)
        (hyperlink-1 :initform nil :accessor slot-hyperlink-1)
        (notebook-1-wxListBox :initform nil :accessor slot-notebook-1-wxListBox)
        (sizer-4 :initform nil :accessor slot-sizer-4)
        (list-box-empty :initform nil :accessor slot-list-box-empty)
        (list-box-filled :initform nil :accessor slot-list-box-filled)
        (notebook-1-wxListCtrl :initform nil :accessor slot-notebook-1-wxListCtrl)
        (sizer-3 :initform nil :accessor slot-sizer-3)
        (list-ctrl-1 :initform nil :accessor slot-list-ctrl-1)
        (notebook-1-wxRadioBox :initform nil :accessor slot-notebook-1-wxRadioBox)
        (grid-sizer-1 :initform nil :accessor slot-grid-sizer-1)
        (radio-box-empty1 :initform nil :accessor slot-radio-box-empty1)
        (radio-box-filled1 :initform nil :accessor slot-radio-box-filled1)
        (radio-box-empty2 :initform nil :accessor slot-radio-box-empty2)
        (radio-box-filled2 :initform nil :accessor slot-radio-box-filled2)
        (notebook-1-wxRadioButton :initform nil :accessor slot-notebook-1-wxRadioButton)
        (sizer-8 :initform nil :accessor slot-sizer-8)
        (grid-sizer-2 :initform nil :accessor slot-grid-sizer-2)
        (radio-btn-1 :initform nil :accessor slot-radio-btn-1)
        (text-ctrl-1 :initform nil :accessor slot-text-ctrl-1)
        (radio-btn-2 :initform nil :accessor slot-radio-btn-2)
        (text-ctrl-2 :initform nil :accessor slot-text-ctrl-2)
        (radio-btn-3 :initform nil :accessor slot-radio-btn-3)
        (text-ctrl-3 :initform nil :accessor slot-text-ctrl-3)
        (notebook-1-wxSlider :initform nil :accessor slot-notebook-1-wxSlider)
        (sizer-22 :initform nil :accessor slot-sizer-22)
        (slider-1 :initform nil :accessor slot-slider-1)
        (notebook-1-wxSpinButton :initform nil :accessor slot-notebook-1-wxSpinButton)
        (sizer-16 :initform nil :accessor slot-sizer-16)
        (tc-spin-button :initform nil :accessor slot-tc-spin-button)
        (spin-button :initform nil :accessor slot-spin-button)
        (notebook-1-wxSpinCtrl :initform nil :accessor slot-notebook-1-wxSpinCtrl)
        (sizer-14 :initform nil :accessor slot-sizer-14)
        (spin-ctrl-1 :initform nil :accessor slot-spin-ctrl-1)
        (notebook-1-wxSplitterWindow-horizontal :initform nil :accessor slot-notebook-1-wxSplitterWindow-horizontal)
        (sizer-29 :initform nil :accessor slot-sizer-29)
        (splitter-1 :initform nil :accessor slot-splitter-1)
        (splitter-1-pane-1 :initform nil :accessor slot-splitter-1-pane-1)
        (sizer-30 :initform nil :accessor slot-sizer-30)
        (label-top-pane :initform nil :accessor slot-label-top-pane)
        (splitter-1-pane-2 :initform nil :accessor slot-splitter-1-pane-2)
        (sizer-31 :initform nil :accessor slot-sizer-31)
        (label-buttom-pane :initform nil :accessor slot-label-buttom-pane)
        (notebook-1-wxSplitterWindow-vertical :initform nil :accessor slot-notebook-1-wxSplitterWindow-vertical)
        (sizer-25 :initform nil :accessor slot-sizer-25)
        (splitter-2 :initform nil :accessor slot-splitter-2)
        (splitter-2-pane-1 :initform nil :accessor slot-splitter-2-pane-1)
        (sizer-32 :initform nil :accessor slot-sizer-32)
        (label-left-pane :initform nil :accessor slot-label-left-pane)
        (splitter-2-pane-2 :initform nil :accessor slot-splitter-2-pane-2)
        (sizer-33 :initform nil :accessor slot-sizer-33)
        (label-right-pane :initform nil :accessor slot-label-right-pane)
        (notebook-1-wxStaticBitmap :initform nil :accessor slot-notebook-1-wxStaticBitmap)
        (sizer-11 :initform nil :accessor slot-sizer-11)
        (bitmap-empty :initform nil :accessor slot-bitmap-empty)
        (bitmap-file :initform nil :accessor slot-bitmap-file)
        (bitmap-nofile :initform nil :accessor slot-bitmap-nofile)
        (bitmap-art :initform nil :accessor slot-bitmap-art)
        (notebook-1-wxStaticLine :initform nil :accessor slot-notebook-1-wxStaticLine)
        (sizer-9 :initform nil :accessor slot-sizer-9)
        (sizer-10 :initform nil :accessor slot-sizer-10)
        (static-line-2 :initform nil :accessor slot-static-line-2)
        (static-line-3 :initform nil :accessor slot-static-line-3)
        (static-line-4 :initform nil :accessor slot-static-line-4)
        (static-line-5 :initform nil :accessor slot-static-line-5)
        (notebook-1-wxStaticText :initform nil :accessor slot-notebook-1-wxStaticText)
        (grid-sizer-3 :initform nil :accessor slot-grid-sizer-3)
        (label-1 :initform nil :accessor slot-label-1)
        (label-4 :initform nil :accessor slot-label-4)
        (label-5 :initform nil :accessor slot-label-5)
        (notebook-1-Spacer :initform nil :accessor slot-notebook-1-Spacer)
        (grid-sizer-4 :initform nil :accessor slot-grid-sizer-4)
        (label-3 :initform nil :accessor slot-label-3)
        (label-2 :initform nil :accessor slot-label-2)
        (notebook-1-wxTextCtrl :initform nil :accessor slot-notebook-1-wxTextCtrl)
        (sizer-18 :initform nil :accessor slot-sizer-18)
        (text-ctrl :initform nil :accessor slot-text-ctrl)
        (notebook-1-wxToggleButton :initform nil :accessor slot-notebook-1-wxToggleButton)
        (sizer-23 :initform nil :accessor slot-sizer-23)
        (button-2 :initform nil :accessor slot-button-2)
        (button-4 :initform nil :accessor slot-button-4)
        (notebook-1-wxTreeCtrl :initform nil :accessor slot-notebook-1-wxTreeCtrl)
        (sizer-24 :initform nil :accessor slot-sizer-24)
        (tree-ctrl-1 :initform nil :accessor slot-tree-ctrl-1)
        (static-line-1 :initform nil :accessor slot-static-line-1)
        (sizer-2 :initform nil :accessor slot-sizer-2)
        (button-5 :initform nil :accessor slot-button-5)
        (button-1 :initform nil :accessor slot-button-1)))

(defun make-All_Widgets_Frame ()
        (let ((obj (make-instance 'All_Widgets_Frame)))
          (init obj)
          (set-properties obj)
          (do-layout obj)
          obj))

(defmethod init ((obj All_Widgets_Frame))
"Method creates the objects contained in the class."
        ;;; begin wxGlade: All_Widgets_Frame.__init__
        (setf (slot-top-window obj) (wxFrame_create nil wxID_ANY "" -1 -1 -1 -1 wxDEFAULT_FRAME_STYLE))
        (slot-top-window obj).wxWindow_SetSize((800, 417))
        (wxFrame_SetTitle (slot-top-window obj) (_"All Widgets"))
        ;;; generating code for setting icons is not implemented
        
        ;;; Menu Bar
        (setf (slot-All-Widgets-menubar obj) (wxMenuBar_Create 0))
        global mn_IDUnix; mn_IDUnix = wxNewId()
        global mn_IDWindows; mn_IDWindows = wxNewId()
        (let ((wxglade_tmp_menu (wxMenu_Create "" 0)))
        (wxMenu_Append wxglade_tmp_menu wxID_OPEN (_"&Open") (_"Open an existing document") 0)
        (wxMenu_Append wxglade_tmp_menu wxID_CLOSE (_"&Close file") (_"Close current document") 0)
        (wxMenu_AppendSeparator wxglade_tmp_menu)
        (wxMenu_Append wxglade_tmp_menu wxID_EXIT (_"E&xit") (_"Finish program") 0)
        		(wxMenuBar_Append (slot-All-Widgets-menubar obj) wxglade_tmp_menu (_"&File")))
        (let ((wxglade_tmp_menu (wxMenu_Create "" 0)))
        (wxMenu_Append wxglade_tmp_menu mn_IDUnix (_"Unix") (_"Use Unix line endings") 2)
        (wxMenu_Append wxglade_tmp_menu mn_IDWindows (_"Windows") (_"Use Windows line endings") 2)
        (wxMenu_AppendSeparator wxglade_tmp_menu)
        (wxMenu_Append wxglade_tmp_menu wxID_ANY (_"Remove Tabs") (_"Remove all leading tabs") 1)
        		(wxMenuBar_Append (slot-All-Widgets-menubar obj) wxglade_tmp_menu (_"&Edit")))
        (let ((wxglade_tmp_menu (wxMenu_Create "" 0)))
        (wxMenu_Append wxglade_tmp_menu wxID_HELP (_"Manual") (_"Show the application manual") 0)
        (wxMenu_AppendSeparator wxglade_tmp_menu)
        (wxMenu_Append wxglade_tmp_menu wxID_ABOUT (_"About") (_"Show the About dialog") 0)
        		(wxMenuBar_Append (slot-All-Widgets-menubar obj) wxglade_tmp_menu (_"&Help")))
        (wxFrame_SetMenuBar (slot-top-window obj) (slot-All-Widgets-menubar obj))
        ;;; Menu Bar end
        
        (setf (slot-All-Widgets-statusbar obj) (wxFrame_CreateStatusBar (slot-top-window obj) 1 wxST_SIZEGRIP))
        (wxStatusBar_SetStatusWidths (slot-All-Widgets-statusbar obj) 1 (vector -1))
        (wxStatusBar_SetStatusText (slot-All-Widgets-statusbar obj) (_"All Widgets statusbar") 0)
        
        ;;; Tool Bar
        (setf (slot-All-Widgets-toolbar obj) (wxToolBar_Create (slot-top-window obj) -1 -1 -1 -1 -1 wxTB_HORIZONTAL))
        (wxToolBar_AddTool (slot-All-Widgets-toolbar obj) wxID_UP (_"UpDown") wxArtProvider_GetBitmap(wxART_GO_UP wxART_OTHER wxSize_Create(32 32)) wxArtProvider_GetBitmap(wxART_GO_DOWN wxART_OTHER wxSize_Create(32 32)) wxITEM_CHECK (_"Up or Down") (_"Up or Down"))
        (wxToolBar_AddTool (slot-All-Widgets-toolbar obj) wxID_OPEN (_"Open") wxBitmap_Create(32 32) wxNullBitmap wxITEM_NORMAL (_"Open a new file") (_"Open a new file"))
        (wxFrame_SetToolBar (slot-top-window obj) (slot-All-Widgets-toolbar obj))
        (wxToolBar_Realize (slot-All-Widgets-toolbar obj))
        ;;; Tool Bar end
        
        (setf (slot-sizer-1 obj) (wxGridSizer_Create 3 1 0 0))
        
        (setf (slot-notebook-1 obj) (wxNotebook_Create (slot-top-window obj) wxID_ANY -1 -1 -1 -1 wxNB_BOTTOM))
        (wxSizer_AddWindow (slot-sizer-1 obj) (slot-notebook-1 obj) 1 wxEXPAND 0 nil)
        
        (setf (slot-notebook-1-wxBitmapButton obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxBitmapButton obj) (_"wxBitmapButton") 1 -1)
        
        (setf (slot-sizer-13 obj) (wxGridSizer_Create 2 2 0 0))
        
        (setf (slot-bitmap-button-icon1 obj) (wxBitmapButton_Create (slot-notebook-1-wxBitmapButton obj) wxID_ANY (wxBitmap_CreateLoad "icon.png" wxBITMAP_TYPE_ANY) -1 -1 -1 -1 0))
        (slot-bitmap-button-icon1 obj).wxWindow_SetSize((slot-bitmap-button-icon1 obj).wxWindow_GetBestSize())
        (wxButton_SetDefault (slot-bitmap-button-icon1 obj))
        (wxSizer_AddWindow (slot-sizer-13 obj) (slot-bitmap-button-icon1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-button-empty1 obj) (wxBitmapButton_Create (slot-notebook-1-wxBitmapButton obj) wxID_ANY wxBitmap_Create(10 10) -1 -1 -1 -1 0))
        (slot-bitmap-button-empty1 obj).wxWindow_SetSize((slot-bitmap-button-empty1 obj).wxWindow_GetBestSize())
        (wxButton_SetDefault (slot-bitmap-button-empty1 obj))
        (wxSizer_AddWindow (slot-sizer-13 obj) (slot-bitmap-button-empty1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-button-icon2 obj) (wxBitmapButton_Create (slot-notebook-1-wxBitmapButton obj) wxID_ANY (wxBitmap_CreateLoad "icon.png" wxBITMAP_TYPE_ANY) -1 -1 -1 -1 (logior wxBORDER_NONE wxBU_BOTTOM)))
        (wxBitmapButton_SetBitmapDisabled (slot-(slot-bitmap-button-icon2 obj) obj) wxBitmap_Create(32 32))
        (slot-bitmap-button-icon2 obj).wxWindow_SetSize((slot-bitmap-button-icon2 obj).wxWindow_GetBestSize())
        (wxButton_SetDefault (slot-bitmap-button-icon2 obj))
        (wxSizer_AddWindow (slot-sizer-13 obj) (slot-bitmap-button-icon2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-button-art obj) (wxBitmapButton_Create (slot-notebook-1-wxBitmapButton obj) wxID_ANY wxArtProvider_GetBitmap(wxART_GO_UP wxART_OTHER wxSize_Create(32 32)) -1 -1 -1 -1 (logior wxBORDER_NONE wxBU_BOTTOM)))
        (slot-bitmap-button-art obj).wxWindow_SetSize((slot-bitmap-button-art obj).wxWindow_GetBestSize())
        (wxButton_SetDefault (slot-bitmap-button-art obj))
        (wxSizer_AddWindow (slot-sizer-13 obj) (slot-bitmap-button-art obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxButton obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxButton obj) (_"wxButton") 1 -1)
        
        (setf (slot-sizer-28 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-button-3 obj) (wxButton_Create (slot-notebook-1-wxButton obj) wxID_BOLD "" -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-28 obj) (slot-button-3 obj) 0 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxCalendarCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxCalendarCtrl obj) (_"wxCalendarCtrl") 1 -1)
        
        (setf (slot-sizer-12 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        ;;; WARNING: Code for instance "calendar-ctrl-1" of "wxCalendarCtrl" not generated: no suitable writer found
        
        
        (setf (slot-notebook-1-wxCheckBox obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxCheckBox obj) (_"wxCheckBox") 1 -1)
        
        (setf (slot-sizer-21 obj) (wxGridSizer_Create 2 3 0 0))
        
        (setf (slot-checkbox-1 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"one (unchecked)") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-1 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-checkbox-2 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"two (checked)") -1 -1 -1 -1 0))
        (wxCheckBox_SetValue (slot-checkbox-2 obj) 1)
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-2 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-checkbox-3 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"three") -1 -1 -1 -1 wxCHK_2STATE))
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-3 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-checkbox-4 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"four (unchecked)") -1 -1 -1 -1 wxCHK_3STATE))
        (wxCheckBox_Set3StateValue (slot-checkbox-4 obj) wxCHK_UNCHECKED)
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-4 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-checkbox-5 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"five (checked)") -1 -1 -1 -1 (logior wxCHK_3STATE wxCHK_ALLOW_3RD_STATE_FOR_USER)))
        (wxCheckBox_Set3StateValue (slot-checkbox-5 obj) wxCHK_CHECKED)
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-5 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-checkbox-6 obj) (wxCheckBox_Create (slot-notebook-1-wxCheckBox obj) wxID_ANY (_"six (undetermined)") -1 -1 -1 -1 (logior wxCHK_3STATE wxCHK_ALLOW_3RD_STATE_FOR_USER)))
        (wxCheckBox_Set3StateValue (slot-checkbox-6 obj) wxCHK_UNDETERMINED)
        (wxSizer_AddWindow (slot-sizer-21 obj) (slot-checkbox-6 obj) 0 wxEXPAND 0 nil)
        
        (setf (slot-notebook-1-wxCheckListBox obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxCheckListBox obj) (_"wxCheckListBox") 1 -1)
        
        (setf (slot-sizer-26 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-check-list-box-1 obj) (wxCheckListBox_Create (slot-notebook-1-wxCheckListBox obj) wxID_ANY -1 -1 -1 -1 4 (vector (_"one") (_"two") (_"three") (_"four")) 0))
        (wxCheckListBox_SetSelection (slot-check-list-box-1 obj) 2)
        (wxSizer_AddWindow (slot-sizer-26 obj) (slot-check-list-box-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxChoice obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxChoice obj) (_"wxChoice") 1 -1)
        
        (setf (slot-sizer-5 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-choice-empty obj) (wxChoice_Create (slot-notebook-1-wxChoice obj) wxID_ANY -1 -1 -1 -1 0 (vector )  0))
        (wxSizer_AddWindow (slot-sizer-5 obj) (slot-choice-empty obj) 1 wxALL 5 nil)
        
        (setf (slot-choice-filled obj) (wxChoice_Create (slot-notebook-1-wxChoice obj) wxID_ANY -1 -1 -1 -1 2 (vector (_"Item 1") (_"Item 2 (pre-selected)"))  0))
        (wxChoice_SetSelection (slot-choice-filled obj) 1)
        (wxSizer_AddWindow (slot-sizer-5 obj) (slot-choice-filled obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxComboBox obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxComboBox obj) (_"wxComboBox") 1 -1)
        
        (setf (slot-sizer-6 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-sizer-7 obj) (wxBoxSizer_Create wxHORIZONTAL))
        (wxSizer_AddSizer (slot-sizer-6 obj) (slot-sizer-7 obj) 1 wxEXPAND 0 nil)
        
        (setf (slot-combo-box-empty obj) (wxComboBox_Create (slot-notebook-1-wxComboBox obj) wxID_ANY "" -1 -1 -1 -1 0 (vector ) 0))
        (wxSizer_AddWindow (slot-sizer-7 obj) (slot-combo-box-empty obj) 1 wxALL 5 nil)
        
        (setf (slot-combo-box-filled obj) (wxComboBox_Create (slot-notebook-1-wxComboBox obj) wxID_ANY "" -1 -1 -1 -1 2 (vector (_"Item 1 (pre-selected)") (_"Item 2")) 0))
        (wxComboBox_SetSelection (slot-combo-box-filled obj) 0)
        (wxSizer_AddWindow (slot-sizer-7 obj) (slot-combo-box-filled obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxDatePickerCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxDatePickerCtrl obj) (_"wxDatePickerCtrl") 1 -1)
        
        (setf (slot-sizer-17 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-datepicker-ctrl-1 obj) (wxDatePickerCtrl_Create (slot-notebook-1-wxDatePickerCtrl obj) wxID_ANY -1 -1 -1 -1 wxDP_SHOWCENTURY))
        (wxSizer_AddWindow (slot-sizer-17 obj) (slot-datepicker-ctrl-1 obj) 1 (logior wxALIGN_CENTER_VERTICAL wxALL) 5 nil)
        
        (setf (slot-notebook-1-wxGauge obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxGauge obj) (_"wxGauge") 1 -1)
        
        (setf (slot-sizer-15 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-gauge-1 obj) (wxGauge_Create (slot-notebook-1-wxGauge obj) wxID_ANY 20 -1 -1 -1 -1 wxGA_HORIZONTAL))
        (wxSizer_AddWindow (slot-sizer-15 obj) (slot-gauge-1 obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxGrid obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxGrid obj) (_"wxGrid") 1 -1)
        
        (setf (slot-sizer-19 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-grid-1 obj) (wxGrid_Create (slot-notebook-1-wxGrid obj) wxID_ANY -1 -1 -1 -1 wxWANTS_CHARS))
        (wxGrid_CreateGrid (slot-grid-1 obj) 10 3 0)
        (wxGrid_SetSelectionMode (slot-grid-1 obj) wxGridSelectRows)
        (wxSizer_AddWindow (slot-sizer-19 obj) (slot-grid-1 obj) 1 wxEXPAND 0 nil)
        
        (setf (slot-notebook-1-wxHyperlinkCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxHyperlinkCtrl obj) (_"wxHyperlinkCtrl") 1 -1)
        
        (setf (slot-sizer-20 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-hyperlink-1 obj) (wxHyperlinkCtrl_Create (slot-notebook-1-wxHyperlinkCtrl obj) wxID_ANY (_"Homepage wxGlade") (_"http://wxglade.sf.net") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-20 obj) (slot-hyperlink-1 obj) 0 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxListBox obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxListBox obj) (_"wxListBox") 1 -1)
        
        (setf (slot-sizer-4 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-list-box-empty obj) (wxListBox_Create (slot-notebook-1-wxListBox obj) wxID_ANY -1 -1 -1 -1 0 (vector ) 0))
        (wxSizer_AddWindow (slot-sizer-4 obj) (slot-list-box-empty obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-list-box-filled obj) (wxListBox_Create (slot-notebook-1-wxListBox obj) wxID_ANY -1 -1 -1 -1 2 (vector (_"Item 1") (_"Item 2 (pre-selected)")) (logior wxLB_MULTIPLE wxLB_SORT)))
        (wxListBox_SetSelection (slot-list-box-filled obj) 1)
        (wxSizer_AddWindow (slot-sizer-4 obj) (slot-list-box-filled obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxListCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxListCtrl obj) (_"wxListCtrl") 1 -1)
        
        (setf (slot-sizer-3 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-list-ctrl-1 obj) (wxListCtrl_Create (slot-notebook-1-wxListCtrl obj) wxID_ANY -1 -1 -1 -1 (logior wxBORDER_SUNKEN wxLC_REPORT)))
        (wxSizer_AddWindow (slot-sizer-3 obj) (slot-list-ctrl-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxRadioBox obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxRadioBox obj) (_"wxRadioBox") 1 -1)
        
        (setf (slot-grid-sizer-1 obj) (wxGridSizer_Create 2 2 0 0))
        
        (setf (slot-radio-box-empty1 obj) (wxRadioBox_Create (slot-notebook-1-wxRadioBox obj) wxID_ANY (_"radio_box_empty1") -1 -1 -1 -1 0 (vector ) 1 wxRA_SPECIFY_ROWS))
        (wxSizer_AddWindow (slot-grid-sizer-1 obj) (slot-radio-box-empty1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-radio-box-filled1 obj) (wxRadioBox_Create (slot-notebook-1-wxRadioBox obj) wxID_ANY (_"radio_box_filled1") -1 -1 -1 -1 3 (vector (_"choice 1") (_"choice 2 (pre-selected)") (_"choice 3")) 0 wxRA_SPECIFY_ROWS))
        (wxRadioBox_SetSelection (slot-radio-box-filled1 obj) 1)
        (wxSizer_AddWindow (slot-grid-sizer-1 obj) (slot-radio-box-filled1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-radio-box-empty2 obj) (wxRadioBox_Create (slot-notebook-1-wxRadioBox obj) wxID_ANY (_"radio_box_empty2") -1 -1 -1 -1 0 (vector ) 1 wxRA_SPECIFY_COLS))
        (wxSizer_AddWindow (slot-grid-sizer-1 obj) (slot-radio-box-empty2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-radio-box-filled2 obj) (wxRadioBox_Create (slot-notebook-1-wxRadioBox obj) wxID_ANY (_"radio_box_filled2") -1 -1 -1 -1 2 (vector (_"choice 1") (_"choice 2 (pre-selected)")) 0 wxRA_SPECIFY_COLS))
        (wxRadioBox_SetSelection (slot-radio-box-filled2 obj) 1)
        (wxSizer_AddWindow (slot-grid-sizer-1 obj) (slot-radio-box-filled2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxRadioButton obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxRadioButton obj) (_"wxRadioButton") 1 -1)
        
        (setf (slot-sizer-8 obj) (StaticBoxSizer_Create (wxStaticBox:wxStaticBox_Create (slot-notebook-1-wxRadioButton obj) (_"My RadioButton Group")) wxHORIZONTAL))
        
        (setf (slot-grid-sizer-2 obj) (wxGridSizer_Create 3 2 0 0))
        (wxSizer_AddSizer (slot-sizer-8 obj) (slot-grid-sizer-2 obj) 1 wxEXPAND 0 nil)
        
        (setf (slot-radio-btn-1 obj) (wxRadioButton_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY (_"Alice") -1 -1 -1 -1 wxRB_GROUP))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-radio-btn-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-text-ctrl-1 obj) (wxTextCtrl_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY "" -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-text-ctrl-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-radio-btn-2 obj) (wxRadioButton_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY (_"Bob") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-radio-btn-2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-text-ctrl-2 obj) (wxTextCtrl_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY "" -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-text-ctrl-2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-radio-btn-3 obj) (wxRadioButton_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY (_"Malroy") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-radio-btn-3 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-text-ctrl-3 obj) (wxTextCtrl_Create (slot-notebook-1-wxRadioButton obj) wxID_ANY "" -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-2 obj) (slot-text-ctrl-3 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxSlider obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxSlider obj) (_"wxSlider") 1 -1)
        
        (setf (slot-sizer-22 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-slider-1 obj) (wxSlider_Create (slot-notebook-1-wxSlider obj) wxID_ANY 5 0 10 -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-22 obj) (slot-slider-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxSpinButton obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxSpinButton obj) (_"wxSpinButton (with wxTextCtrl)") 1 -1)
        
        (setf (slot-sizer-16 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-tc-spin-button obj) (wxTextCtrl_Create (slot-notebook-1-wxSpinButton obj) wxID_ANY (_"1") -1 -1 -1 -1 wxTE_RIGHT))
        (wxSizer_AddWindow (slot-sizer-16 obj) (slot-tc-spin-button obj) 1 wxALL 5 nil)
        
        (setf (slot-spin-button obj) (wxSpinButton_Create (slot-notebook-1-wxSpinButton obj) wxID_ANY -1 -1 -1 -1 wxSP_VERTICAL))
        (wxSizer_AddWindow (slot-sizer-16 obj) (slot-spin-button obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxSpinCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxSpinCtrl obj) (_"wxSpinCtrl") 1 -1)
        
        (setf (slot-sizer-14 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-spin-ctrl-1 obj) (wxSpinCtrl_Create (slot-notebook-1-wxSpinCtrl obj) wxID_ANY 4 -1 -1 -1 -1 wxSP_ARROW_KEYS 0 100 4))
        (wxSizer_AddWindow (slot-sizer-14 obj) (slot-spin-ctrl-1 obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxSplitterWindow-horizontal obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxScrolledWindow:wxScrolledWindow_SetScrollRate (slot-notebook-1-wxSplitterWindow-horizontal obj) 10  10)
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxSplitterWindow-horizontal obj) (_"wxSplitterWindow (horizontally)") 1 -1)
        
        (setf (slot-sizer-29 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-splitter-1 obj) (wxSplitterWindow_Create (slot-notebook-1-wxSplitterWindow-horizontal obj) wxID_ANY -1 -1 -1 -1 0))
        wxSplitterWindow_SetMinimumPaneSize (slot-splitter-1 obj) 20)
        (wxSizer_AddWindow (slot-sizer-29 obj) (slot-splitter-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-splitter-1-pane-1 obj) (wxPanel_Create (slot-splitter-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        
        (setf (slot-sizer-30 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-label-top-pane obj) (wxStaticText_Create (slot-splitter-1-pane-1 obj) wxID_ANY (_"top pane") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-30 obj) (slot-label-top-pane obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-splitter-1-pane-2 obj) (wxPanel_Create (slot-splitter-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        
        (setf (slot-sizer-31 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-label-buttom-pane obj) (wxStaticText_Create (slot-splitter-1-pane-2 obj) wxID_ANY (_"bottom pane") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-31 obj) (slot-label-buttom-pane obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxSplitterWindow-vertical obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxScrolledWindow:wxScrolledWindow_SetScrollRate (slot-notebook-1-wxSplitterWindow-vertical obj) 10  10)
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxSplitterWindow-vertical obj) (_"wxSplitterWindow (vertically)") 1 -1)
        
        (setf (slot-sizer-25 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-splitter-2 obj) (wxSplitterWindow_Create (slot-notebook-1-wxSplitterWindow-vertical obj) wxID_ANY -1 -1 -1 -1 0))
        wxSplitterWindow_SetMinimumPaneSize (slot-splitter-2 obj) 20)
        (wxSizer_AddWindow (slot-sizer-25 obj) (slot-splitter-2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-splitter-2-pane-1 obj) (wxPanel_Create (slot-splitter-2 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        
        (setf (slot-sizer-32 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-label-left-pane obj) (wxStaticText_Create (slot-splitter-2-pane-1 obj) wxID_ANY (_"left pane") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-32 obj) (slot-label-left-pane obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-splitter-2-pane-2 obj) (wxPanel_Create (slot-splitter-2 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        
        (setf (slot-sizer-33 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-label-right-pane obj) (wxStaticText_Create (slot-splitter-2-pane-2 obj) wxID_ANY (_"right pane") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-33 obj) (slot-label-right-pane obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxStaticBitmap obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxStaticBitmap obj) (_"wxStaticBitmap") 1 -1)
        
        (setf (slot-sizer-11 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-bitmap-empty obj) (wxStaticBitmap_Create (slot-notebook-1-wxStaticBitmap obj) wxID_ANY  wxBitmap_Create(32 32) -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-11 obj) (slot-bitmap-empty obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-file obj) (wxStaticBitmap_Create (slot-notebook-1-wxStaticBitmap obj) wxID_ANY  (wxBitmap_CreateLoad "icon.png" wxBITMAP_TYPE_ANY) -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-11 obj) (slot-bitmap-file obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-nofile obj) (wxStaticBitmap_Create (slot-notebook-1-wxStaticBitmap obj) wxID_ANY  (wxBitmap_CreateLoad "non-existing.bmp" wxBITMAP_TYPE_ANY) -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-11 obj) (slot-bitmap-nofile obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-bitmap-art obj) (wxStaticBitmap_Create (slot-notebook-1-wxStaticBitmap obj) wxID_ANY  wxArtProvider_GetBitmap(wxART_PRINT wxART_OTHER wxSize_Create(32 32)) -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-11 obj) (slot-bitmap-art obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxStaticLine obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxStaticLine obj) (_"wxStaticLine") 1 -1)
        
        (setf (slot-sizer-9 obj) (wxBoxSizer_Create wxVERTICAL))
        
        (setf (slot-sizer-10 obj) (wxBoxSizer_Create wxHORIZONTAL))
        (wxSizer_AddSizer (slot-sizer-9 obj) (slot-sizer-10 obj) 1 wxEXPAND 0 nil)
        
        (setf (slot-static-line-2 obj) (wxStaticLine_Create (slot-notebook-1-wxStaticLine obj) wxID_ANY -1 -1 -1 -1 wxLI_VERTICAL))
        (wxSizer_AddWindow (slot-sizer-10 obj) (slot-static-line-2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-static-line-3 obj) (wxStaticLine_Create (slot-notebook-1-wxStaticLine obj) wxID_ANY -1 -1 -1 -1 wxLI_VERTICAL))
        (wxSizer_AddWindow (slot-sizer-10 obj) (slot-static-line-3 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-static-line-4 obj) (wxStaticLine_Create (slot-notebook-1-wxStaticLine obj) wxID_ANY -1 -1 -1 -1 wxLI_HORIZONTAL))
        (wxSizer_AddWindow (slot-sizer-9 obj) (slot-static-line-4 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-static-line-5 obj) (wxStaticLine_Create (slot-notebook-1-wxStaticLine obj) wxID_ANY -1 -1 -1 -1 wxLI_HORIZONTAL))
        (wxSizer_AddWindow (slot-sizer-9 obj) (slot-static-line-5 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxStaticText obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxStaticText obj) (_"wxStaticText") 1 -1)
        
        (setf (slot-grid-sizer-3 obj) (wxGridSizer_Create 1 3 0 0))
        
        (setf (slot-label-1 obj) (wxStaticText_Create (slot-notebook-1-wxStaticText obj) wxID_ANY (_"red text (RGB)") -1 -1 -1 -1 wxALIGN_CENTER_HORIZONTAL))
        (wxWindow_SetForegroundColour (slot-label-1 obj) (wxColour_CreateRGB 255, 0, 0))
        (wxSizer_AddWindow (slot-grid-sizer-3 obj) (slot-label-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-label-4 obj) (wxStaticText_Create (slot-notebook-1-wxStaticText obj) wxID_ANY (_"black on red (RGB)") -1 -1 -1 -1 wxALIGN_CENTER_HORIZONTAL))
        (wxWindow_SetBackgroundColour (slot-label-4 obj) (wxColour_CreateRGB 255, 0, 0))
        (wxWindow_SetToolTip (slot-label-4 obj)(_"Background colour won't show, check documentation for more details"))
        (wxSizer_AddWindow (slot-grid-sizer-3 obj) (slot-label-4 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-label-5 obj) (wxStaticText_Create (slot-notebook-1-wxStaticText obj) wxID_ANY (_"green on pink (RGB)") -1 -1 -1 -1 wxALIGN_CENTER_HORIZONTAL))
        (wxWindow_SetBackgroundColour (slot-label-5 obj) (wxColour_CreateRGB 255, 0, 255))
        (wxWindow_SetForegroundColour (slot-label-5 obj) (wxColour_CreateRGB 0, 255, 0))
        (wxWindow_SetToolTip (slot-label-5 obj)(_"Background colour won't show, check documentation for more details"))
        (wxSizer_AddWindow (slot-grid-sizer-3 obj) (slot-label-5 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-Spacer obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-Spacer obj) (_"Spacer") 1 -1)
        
        (setf (slot-grid-sizer-4 obj) (wxGridSizer_Create 1 3 0 0))
        
        (setf (slot-label-3 obj) (wxStaticText_Create (slot-notebook-1-Spacer obj) wxID_ANY (_"Two labels with a") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-4 obj) (slot-label-3 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (wxSizer_AddWindow (slot-grid-sizer-4 obj) ((60, 20) obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-label-2 obj) (wxStaticText_Create (slot-notebook-1-Spacer obj) wxID_ANY (_"spacer between") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-grid-sizer-4 obj) (slot-label-2 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxTextCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxTextCtrl obj) (_"wxTextCtrl") 1 -1)
        
        (setf (slot-sizer-18 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-text-ctrl obj) (wxTextCtrl_Create (slot-notebook-1-wxTextCtrl obj) wxID_ANY (_"This\nis\na\nmultiline\nwxTextCtrl") -1 -1 -1 -1 (logior wxTE_CHARWRAP wxTE_MULTILINE wxTE_WORDWRAP)))
        (wxSizer_AddWindow (slot-sizer-18 obj) (slot-text-ctrl obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-notebook-1-wxToggleButton obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxToggleButton obj) (_"wxToggleButton") 1 -1)
        
        (setf (slot-sizer-23 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-button-2 obj) (wxToggleButton_Create (slot-notebook-1-wxToggleButton obj) wxID_ANY (_"Toggle Button 1") -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-23 obj) (slot-button-2 obj) 1 wxALL 5 nil)
        
        (setf (slot-button-4 obj) (wxToggleButton_Create (slot-notebook-1-wxToggleButton obj) wxID_ANY (_"Toggle Button 2") -1 -1 -1 -1 (logior wxBU_BOTTOM wxBU_EXACTFIT)))
        (wxSizer_AddWindow (slot-sizer-23 obj) (slot-button-4 obj) 1 wxALL 5 nil)
        
        (setf (slot-notebook-1-wxTreeCtrl obj) (wxPanel_Create (slot-notebook-1 obj) wxID_ANY -1 -1 -1 -1 wxTAB_TRAVERSAL))
        (wxNotebook_AddPage (slot-notebook-1 obj) (slot-notebook-1-wxTreeCtrl obj) (_"wxTreeCtrl") 1 -1)
        
        (setf (slot-sizer-24 obj) (wxBoxSizer_Create wxHORIZONTAL))
        
        (setf (slot-tree-ctrl-1 obj) (wxTreeCtrl_Create (slot-notebook-1-wxTreeCtrl obj) wxID_ANY -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-24 obj) (slot-tree-ctrl-1 obj) 1 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-static-line-1 obj) (wxStaticLine_Create (slot-top-window obj) wxID_ANY -1 -1 -1 -1 wxLI_HORIZONTAL))
        (wxSizer_AddWindow (slot-sizer-1 obj) (slot-static-line-1 obj) 0 (logior wxALL wxEXPAND) 5 nil)
        
        (setf (slot-sizer-2 obj) (wxGridSizer_Create 1 2 0 0))
        (wxSizer_AddSizer (slot-sizer-1 obj) (slot-sizer-2 obj) 0 wxALIGN_RIGHT 0 nil)
        
        (setf (slot-button-5 obj) (wxButton_Create (slot-top-window obj) wxID_CLOSE "" -1 -1 -1 -1 0))
        (wxSizer_AddWindow (slot-sizer-2 obj) (slot-button-5 obj) 0 (logior wxALIGN_RIGHT wxALL) 5 nil)
        
        (setf (slot-button-1 obj) (wxButton_Create (slot-top-window obj) wxID_OK "" -1 -1 -1 -1 wxBU_TOP))
        (wxSizer_AddWindow (slot-sizer-2 obj) (slot-button-1 obj) 0 (logior wxALIGN_RIGHT wxALL) 5 nil)
        
        (wxWindow_SetSizer (slot-notebook-1-wxTreeCtrl obj) (slot-sizer-24 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxToggleButton obj) (slot-sizer-23 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxTextCtrl obj) (slot-sizer-18 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-Spacer obj) (slot-grid-sizer-4 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxStaticText obj) (slot-grid-sizer-3 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxStaticLine obj) (slot-sizer-9 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxStaticBitmap obj) (slot-sizer-11 obj))
        
        (wxWindow_SetSizer (slot-splitter-2-pane-2 obj) (slot-sizer-33 obj))
        
        (wxWindow_SetSizer (slot-splitter-2-pane-1 obj) (slot-sizer-32 obj))
        
        (SplitVertically splitter-2 splitter_2_pane_1 splitter_2_pane_2 )
        
        (wxWindow_SetSizer (slot-notebook-1-wxSplitterWindow-vertical obj) (slot-sizer-25 obj))
        
        (wxWindow_SetSizer (slot-splitter-1-pane-2 obj) (slot-sizer-31 obj))
        
        (wxWindow_SetSizer (slot-splitter-1-pane-1 obj) (slot-sizer-30 obj))
        
        (SplitHorizontally splitter-1 splitter_1_pane_1 splitter_1_pane_2 )
        
        (wxWindow_SetSizer (slot-notebook-1-wxSplitterWindow-horizontal obj) (slot-sizer-29 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxSpinCtrl obj) (slot-sizer-14 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxSpinButton obj) (slot-sizer-16 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxSlider obj) (slot-sizer-22 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxRadioButton obj) (slot-sizer-8 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxRadioBox obj) (slot-grid-sizer-1 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxListCtrl obj) (slot-sizer-3 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxListBox obj) (slot-sizer-4 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxHyperlinkCtrl obj) (slot-sizer-20 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxGrid obj) (slot-sizer-19 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxGauge obj) (slot-sizer-15 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxDatePickerCtrl obj) (slot-sizer-17 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxComboBox obj) (slot-sizer-6 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxChoice obj) (slot-sizer-5 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxCheckListBox obj) (slot-sizer-26 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxCheckBox obj) (slot-sizer-21 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxCalendarCtrl obj) (slot-sizer-12 obj))
        
        (wxWindow_SetSizer (slot-notebook-1-wxButton obj) (slot-sizer-28 obj))
        
        (wxFlexGridSizer_AddGrowableRow (slot-sizer-13 obj) 0)
        (wxFlexGridSizer_AddGrowableRow (slot-sizer-13 obj) 1)
        (wxFlexGridSizer_AddGrowableCol (slot-sizer-13 obj) 0)
        (wxFlexGridSizer_AddGrowableCol (slot-sizer-13 obj) 1)
        (wxWindow_SetSizer (slot-notebook-1-wxBitmapButton obj) (slot-sizer-13 obj))
        
        (wxFlexGridSizer_AddGrowableRow (slot-sizer-1 obj) 0)
        (wxFlexGridSizer_AddGrowableCol (slot-sizer-1 obj) 0)
        (wxWindow_SetSizer (slot-frame obj) (slot-sizer-1 obj))
        (wxSizer_SetSizeHints (slot-slot-sizer-1 obj) (slot-frame obj))
        
        (wxFrame_layout (slot-All-Widgets self))
        (wxFrame_Centre (slot-top-window obj) wxBOTH)

        (wxEvtHandler_Connect (slot-top-window obj) obj.notebook-1 (expwxEVT_NOTEBOOK_PAGE_CHANGED)
        (wxClosure_Create #'OnNotebookPageChanged obj))
        (wxEvtHandler_Connect (slot-top-window obj) obj.notebook-1 (expwxEVT_NOTEBOOK_PAGE_CHANGING)
        (wxClosure_Create #'OnNotebookPageChanging obj))
        (wxEvtHandler_Connect (slot-top-window obj) obj.button-1 (expwxEVT_BUTTON)
        (wxClosure_Create #'onStartConverting obj))
        ;;; end wxGlade
        )

(defun OnNotebookPageChanged (function data event) ;;; wxGlade: All_Widgets_Frame.<event_handler>
        (print "Event handler 'OnNotebookPageChanged' not implemented!")
        (when event
                (wxEvent:wxEvent_Skip event)))

(defun OnNotebookPageChanging (function data event) ;;; wxGlade: All_Widgets_Frame.<event_handler>
        (print "Event handler 'OnNotebookPageChanging' not implemented!")
        (when event
                (wxEvent:wxEvent_Skip event)))

(defun onStartConverting (function data event) ;;; wxGlade: All_Widgets_Frame.<event_handler>
        (print "Event handler 'onStartConverting' not implemented!")
        (when event
                (wxEvent:wxEvent_Skip event)))

;;; end of class All_Widgets_Frame


(defun init-func (fun data evt)
    (setf (textdomain) "AllWidgets28App") ;; replace with the appropriate catalog name
    (defun _ (msgid) (gettext msgid "AllWidgets28App"))

    (let ((All-Widgets (make-All_Widgets_Frame)))
    (ELJApp_SetTopWindow (slot-top-window All-Widgets))
    (wxWindow_Show (slot-top-window All-Widgets))))

(unwind-protect
    (Eljapp_initializeC (wxclosure_Create #'init-func nil) 0 nil)
    (ffi:close-foreign-library "../miscellaneous/wxc-msw2.6.2.dll"))
