// -*- C++ -*-
//
// generated by wxGlade 034d891cc947+ on Sat Nov  5 21:42:16 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "bug192.h"

// begin wxGlade: ::extracode
// end wxGlade



Frame192::Frame192(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, style)
{
    // begin wxGlade: Frame192::Frame192
    button_2 = new wxButton(this, wxID_CANCEL, wxEmptyString);
    button_1 = new wxButton(this, wxID_OK, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void Frame192::set_properties()
{
    // begin wxGlade: Frame192::set_properties
    SetTitle(_("frame_1"));
    SetSize(wxSize(300, 300));
    button_2->SetDefault();
    // end wxGlade
}


void Frame192::do_layout()
{
    // begin wxGlade: Frame192::do_layout
    sizer_as_attr = new wxFlexGridSizer(3, 1, 0, 0);
    wxBoxSizer* sizer_local = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, _("Just a text"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER);
    sizer_as_attr->Add(label_1, 1, wxALIGN_CENTER|wxALL|wxEXPAND|wxSHAPED, 5);
    wxStaticLine* static_line_1 = new wxStaticLine(this, wxID_ANY);
    sizer_as_attr->Add(static_line_1, 0, wxALL|wxEXPAND, 5);
    sizer_local->Add(button_2, 0, 0, 0);
    sizer_local->Add(button_1, 0, 0, 0);
    sizer_as_attr->Add(sizer_local, 1, wxALIGN_RIGHT|wxALL, 5);
    SetSizer(sizer_as_attr);
    sizer_as_attr->SetSizeHints(this);
    sizer_as_attr->AddGrowableRow(0);
    sizer_as_attr->AddGrowableCol(0);
    Layout();
    // end wxGlade
}


class MyApp: public wxApp {
public:
    bool OnInit();
protected:
    wxLocale m_locale;  // locale we'll be using
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    m_locale.Init();
#ifdef APP_LOCALE_DIR
    m_locale.AddCatalogLookupPathPrefix(wxT(APP_LOCALE_DIR));
#endif
    m_locale.AddCatalog(wxT(APP_CATALOG));

    wxInitAllImageHandlers();
    Frame192* Bug192_Frame = new Frame192(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(Bug192_Frame);
    Bug192_Frame->Show();
    return true;
}
