// -*- C++ -*-
//
// generated by wxGlade "faked test version"
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

// This is an automatically generated file.
// Manual changes will be overwritten without warning!

#include <wx/wx.h>
#include <wx/image.h>
#include "MyAppFrame.h"


class MyStartApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyStartApp)

bool MyStartApp::OnInit()
{
    wxInitAllImageHandlers();
    MyAppFrame* appframe = new MyAppFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(appframe);
    appframe->Show();
    return true;
}
