#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0 on Sat Mar  9 15:11:06 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MeasurementFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MeasurementFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 340))
        self.panel_3 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MeasurementFrame.__set_properties
        self.SetTitle("ATV Tester")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MeasurementFrame.__do_layout
        sizer_limit = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self.panel_3, wx.ID_ANY, "History"), wx.VERTICAL)
        self.panel_3.SetSizer(sizer_8)
        sizer_limit.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_limit)
        self.Layout()
        # end wxGlade

# end of class MeasurementFrame

class App(wx.App):
    def OnInit(self):
        self.frame = MeasurementFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class App

if __name__ == "__main__":
    App = App(0)
    App.MainLoop()
