# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Sat Aug 10 13:49:28 2019
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
#include "bitmapFromMem.h"
#ifndef ICON_XPM
#define ICON_XPM
#include "res/multivnc.xpm"
#endif
# end wxGlade


class FrameMain(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrameMain.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle(_("Frame"))
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.ICON(icon))
        self.SetIcon(_icon)
        self.SetSize((985, 852))
        
        sizer_top = wx.BoxSizer(wx.HORIZONTAL)
        
        self.panel_top = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_STATIC | wx.TAB_TRAVERSAL)
        sizer_top.Add(self.panel_top, 1, wx.EXPAND, 0)
        
        self.SetSizer(sizer_top)
        
        self.Layout()
        # end wxGlade

# end of class FrameMain
