// -*- C++ -*-
//
// generated by wxGlade "faked test version"
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "styleless-dialog.h"

// begin wxGlade: ::extracode
// end wxGlade



StylelessDialog::StylelessDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
{
    // begin wxGlade: StylelessDialog::StylelessDialog

    set_properties();
    do_layout();
    // end wxGlade
}


void StylelessDialog::set_properties()
{
    // begin wxGlade: StylelessDialog::set_properties
    SetTitle(_("Style-less Dialog"));
    // end wxGlade
}


void StylelessDialog::do_layout()
{
    // begin wxGlade: StylelessDialog::do_layout
    Layout();
    // end wxGlade
}


StylelessFrame::StylelessFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, style)
{
    // begin wxGlade: StylelessFrame::StylelessFrame

    set_properties();
    do_layout();
    // end wxGlade
}


void StylelessFrame::set_properties()
{
    // begin wxGlade: StylelessFrame::set_properties
    SetTitle(_("Style-less Frame"));
    // end wxGlade
}


void StylelessFrame::do_layout()
{
    // begin wxGlade: StylelessFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}


class MyApp: public wxApp {
public:
    bool OnInit();
protected:
    wxLocale m_locale;  // locale we'll be using
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    m_locale.Init();
#ifdef APP_LOCALE_DIR
    m_locale.AddCatalogLookupPathPrefix(wxT(APP_LOCALE_DIR));
#endif
    m_locale.AddCatalog(wxT(APP_CATALOG));

    wxInitAllImageHandlers();
    StylelessDialog* dialog = new StylelessDialog(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(dialog);
    dialog->Show();
    return true;
}
