# -*- coding: ISO-8859-15 -*-
#
# generated by wxGlade
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class StylelessDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StylelessDialog.__init__
        kwds["style"] = kwds.get("style", 0)
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: StylelessDialog.__set_properties
        self.SetTitle(_("Style-less Dialog"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: StylelessDialog.__do_layout
        self.Layout()
        # end wxGlade

# end of class StylelessDialog

class StylelessFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StylelessFrame.__init__
        kwds["style"] = kwds.get("style", 0)
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: StylelessFrame.__set_properties
        self.SetTitle(_("Style-less Frame"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: StylelessFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class StylelessFrame
