// -*- C++ -*-
//
// generated by wxGlade 0.9.9pre on Sun Jul 19 13:03:36 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef TEST_GRID_CUSTOM_BASE_H
#define TEST_GRID_CUSTOM_BASE_H

#include <wx/wx.h>
#include <wx/image.h>

#include <wx/grid.h>

import my_grid


class TestGlade: public wxPanel {
public:
    TestGlade(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: TestGlade::attributes
    my_grid.MyGrid* grid;
    // end wxGlade
}; // wxGlade: end class


#endif // TEST_GRID_CUSTOM_BASE_H
