// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef TOPLEVEL_EXTRACODE_H
#define TOPLEVEL_EXTRACODE_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
# frame extra code
# dialog extra code
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: MyFrame::attributes
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_close_frame(wxCloseEvent &event); // wxGlade: <event_handler>
    virtual void on_menu_close_frame(MenuEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class MyDialog: public wxDialog {
public:
    // begin wxGlade: MyDialog::ids
    // end wxGlade

    MyDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: MyDialog::attributes
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_close_dialog(wxCloseEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class MyMenuBar: public wxMenuBar {
public:
    // begin wxGlade: MyMenuBar::ids
    // end wxGlade

    MyMenuBar();

private:

protected:
    // begin wxGlade: MyMenuBar::attributes
    // end wxGlade
}; // wxGlade: end class


class wxToolBar: public wxToolBar {
public:
    // begin wxGlade: wxToolBar::ids
    // end wxGlade

    wxToolBar(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxTB_HORIZONTAL|wxNO_BORDER);

private:

protected:
    // begin wxGlade: wxToolBar::attributes
    // end wxGlade
}; // wxGlade: end class


class MyDialog1: public wxPanel {
public:
    // begin wxGlade: MyDialog1::ids
    // end wxGlade

    MyDialog1(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: MyDialog1::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // TOPLEVEL_EXTRACODE_H
