class ButtonStockItems(object):

    stock_ids = {
        "ADD" :                 "Add",
        "APPLY" :               "&Apply",
        "BACKWARD" :            "&Back",
        "BOLD" :                "&Bold",
        "BOTTOM" :              "&Bottom",
        "CANCEL" :              "&Cancel",
        "CDROM" :               "CD-Rom",
        "CLEAR" :               "&Clear",
        "CLOSE" :               "&Close",
        "CONVERT" :             "&Convert",
        "COPY" :                "&Copy",
        "CUT" :                 "Cu&t",
        "DELETE" :              "&Delete",
        "DOWN" :                "&Down",
        "EDIT" :                "&Edit",
        "EXECUTE" :             "&Execute",
        "EXIT" :                "&Quit",
        "FIND" :                "&Find",
        "FIRST" :               "&First",
        "FLOPPY" :              "&Floppy",
        "FORWARD" :             "&Forward",
        "HARDDISK" :            "&Harddisk",
        "HELP" :                "&Help",
        "HOME" :                "&Home",
        "INDENT" :              "Indent",
        "INDEX" :               "&Index",
        "INFO" :                "&Info",
        "ITALIC" :              "&Italic",
        "JUMP_TO" :             "&Jump to",
        "JUSTIFY_CENTER" :      "Centered",
        "JUSTIFY_FILL" :        "Justified",
        "JUSTIFY_LEFT" :        "Align Left",
        "JUSTIFY_RIGHT" :       "Align Right",
        "LAST" :                "&Last",
        "NETWORK" :             "&Network",
        "NEW" :                 "&New",
        "NO" :                  "&No",
        "OK" :                  "&OK",
        "OPEN" :                "&Open",
        "PASTE" :               "&Paste",
        "PREFERENCES" :         "&Preferences",
        "PREVIEW" :             "Print previe&w",
        "PRINT" :               "&Print",
        "PROPERTIES" :          "&Properties",
        "REDO" :                "&Redo",
        "REFRESH" :             "Refresh",
        "REMOVE" :              "Remove",
        "REPLACE" :             "Find and rep&lace",
        "REVERT_TO_SAVED" :     "Revert to Saved",
        "SAVE" :                "&Save",
        "SAVEAS" :              "Save &As...",
        "SELECTALL" :           "Select &All",
        "SELECT_COLOR" :        "&Color",
        "SELECT_FONT" :         "&Font",
        "SORT_ASCENDING" :      "&Ascending",
        "SORT_DESCENDING" :     "&Descending",
        "SPELL_CHECK" :         "&Spell Check",
        "STOP" :                "&Stop",
        "STRIKETHROUGH" :       "&Strikethrough",
        "TOP" :                 "&Top",
        "UNDELETE" :            "Undelete",
        "UNDERLINE" :           "&Underline",
        "UNDO" :                "&Undo",
        "UNINDENT" :            "&Unindent",
        "UP" :                  "&Up",
        "YES" :                 "&Yes",
        "ZOOM_100" :            "&Actual Size",
        "ZOOM_FIT" :            "Zoom to &Fit",
        "ZOOM_IN" :             "Zoom &In",
        "ZOOM_OUT" :            "Zoom &Out",
    }
